version: "3.9"
services:
  cxthsql:
    build: .
    hostname: CXPES
    ports:
      - "1433:1433"
    volumes:
      - ${LIQUIBASE_SCRIPTS_DIR}:/mnt/liquibase-scripts
  mesh:
    image: ncr-fsg-ess-docker-releases.jfrog.io/com/ncr/cxp:${MESH_VERSION}
    depends_on:
      - "cxthsql"
    environment:
      - PROPERTY_ENCRYPTION_PASSWORD=nep
      - SA_PASSWORD=${SA_PASSWORD}
    ports:
      - "80:8080"
    volumes:
      - ${NCR_DIR}:/mnt/ncr
