version: "3.9"
services:
  cxthsql:
    build: .
    hostname: CXPES
    ports:
      - "1433:1433"
    volumes:
      - /c/ncrdev/liquibase-scripts:/mnt/liquibase-scripts
  mesh:
    image: ncr-fsg-ess-docker-releases.jfrog.io/com/ncr/cxp:${MESH_VERSION}
    environment:
      - PROPERTY_ENCRYPTION_PASSWORD=nep
    ports:
      - "80:8080"
    volumes:
      - ${MESH_DATALOAD_DIR}:/mnt/ncr